### ISSUE TITLE
Update Problem

### ISSUE THREAD

**Issue by jannnfe** [iomax/homebridge-mqttgaragedoor#1]
Hello,
If the garage is closed and I open it, and I stop it in the middle, then nothing works anymore. How exactly does the plugin work? What values ​​must the various topics have?
Thanks

**Comment by iomax** [comment]
Could you provide some more info about your setup and what do you means by
"nothing works anymore" ?

Could you tell me something more about your config.js and following param ?

*  "topics": {
		"statusSet":    "MQTT TOPIC FOR THE SETTING THE STATUS"
		"openGet":      "OPTIONAL MQTT TOPIC FOR THE GETTING THE STATUS OF
OPEN SWITCH",
		"closedGet":    "OPTIONAL MQTT TOPIC FOR THE GETTING THE STATUS OF
CLOSED SWITCH",
		"openValue":    "OPTIONAL VALUE THAT MEANS OPEN (DEFAULT true)"
		"closedValue":  "OPTIONAL VALUE THAT MEANS CLOSED (DEFAULT true)"
            }
  "doorRunInSeconds": "OPEN/CLOSE RUN TIME IN SECONDS",
  "pauseInSeconds" : "IF DEFINED : AUTO CLOSE AFTER [Seconds]"
*

**Comment by jannnfe** [comment]
I have a Sonoff Basic with Tasmota Firmware running and PulseTime enable.
I connected a Reed Sensor to the Relay. The Reed Sensor is on Topic cmnd/Garagentor_Sensor/POWER1

"topics": {
		"statusSet":    "cmnd/Garagentor/POWER",
		"openGet":      "cmnd/Garagentor_Sensor/POWER1",
		"closedGet":    "cmnd/Garagentor_Sensor/POWER1",
		"openValue":    "ON",
		"closedValue":  "OFF"
            }
"doorRunInSeconds": "<Nothing defined>",
"pauseInSeconds" : "<Nothing defined>"

I mean that homebridge displays open... while the door is closed or it displays opend and it is actually closed. I don't know how to describe the issue right because i don't know much about mqtt sorry :(

**Comment by iomax** [comment]
One reed sensor can provide just the info about door status closed or full opened not both so you have to use the "Sensor" topic just for the right param ( openGet or closeGet) instead of both.
In this case the doorRunInSeconds  can be used to show  the running time ( opening or closing info in the home app ) up to the final state otherwise you can leave it and the home app will reflect the reed status without any "running" feedback.

**Comment by iomax** [comment]
Any news ?
