### ISSUE TITLE
pauseInSeconds

### ISSUE THREAD

**Issue by hejsiri** [iomax/homebridge-mqttgaragedoor#11]
`"pauseInSeconds" : "30"`

How work this options? I defined the value for 30 seconds but the garage doot did not close.

**Comment by iomax** [comment]
"pauseInSeconds" : 30 <--- Numeric.

Door auto-closure must be manage by the door/motor controller, "pauseInSeconds" just keep the home(kit) app updated as close as possible about the door state ( "closing" in this case state ) where only the "closed" ( or none ) switch is present and the door controller auto-closure option configured.
