### ISSUE TITLE
Help needed on plugin config when no contact/reed sensor

### ISSUE THREAD

**Issue by peros550** [iomax/homebridge-mqttgaragedoor#14]
Hi, 
I would like to use your plugin but I need some help and guidance.

The board I'm using is a custom made board based on Arduino. Right now the board subscribes and listens for commands on the following three topics: 
a) Output 1 --> OPEN command --> cmnd/Output1/POWER (ON or OFF)
b) Output 2 --> CLOSE command --> cmnd/Output2/POWER (ON or OFF)
c) Output 3 --> STOP command --> cmnd/Output3/POWER (ON or OFF)

When ON command is received, the relevant output stays ON for 1,5sec and returns back to OFF publishing the status to the mqtt broker. 

There is no contact/reed to my setup. 

My problem is, I really don't know how to setup the config so that it works with your plugin.

**Comment by iomax** [comment]
This plug-in can operate in someway without any contact/reed ( so no realtime feedback get by the door ) but do work trough a single cmd topic ( "statusSet" ) instead your board do expect different cmd topic for every action ( one to open, one to close and one to stop ).
Sorry, no option to work.

**Comment by peros550** [comment]
ok thanks!
