### ISSUE TITLE
Accessorie not loadable

### ISSUE THREAD

**Issue by Stephan811D** [iomax/homebridge-mqttgaragedoor#15]
Hi,

i have a problem with the mqttgaragedoor accessorie.

After starting homebridge i get the following log:
![image](https://user-images.githubusercontent.com/37579239/56853234-34ad7480-6925-11e9-931e-ade4909a390a.png)

plus the this error-message: 
![image](https://user-images.githubusercontent.com/37579239/56853238-5575ca00-6925-11e9-9421-89a2adac3895.png)

my config.json-file looks like that:

![image](https://user-images.githubusercontent.com/37579239/56853255-8950ef80-6925-11e9-84b8-9b134973e2aa.png)

as the log says homebridge exited with a failure.

Any ideas?

**Comment by iomax** [comment]
In my setup I get `Registering accessory 'homebridge-mqttgaragedoor.mqttgaragedoor`
I can not help on this side but I'd try "accessory": "MqttGarage" in your config.

**Comment by Stephan811D** [comment]
the problem was i installed it with sudo npm install -g homebridge-mqttgaragedoor which installed the following `https://github.com/tvillingett/homebridge-mqttgaragedoor`

**Comment by iomax** [comment]
Without cloning it locally I'd try `npm install -g iomax/homebridge-mqttgaragedoor`.
Please let me know if it works. Thanks
