### ISSUE TITLE
Can't install..

### ISSUE THREAD

**Issue by manimac79** [iomax/homebridge-mqttgaragedoor#16]
Hello, maybe i'm a total newbie on homebridge but... I'm not able to install this plugin on my homebridge setup. I've done this steps:
1. git clone https://github.com/iomax/homebridge-mqttgaragedoor.git
2. npm install -g ./homebridge-mqttgaragedoor (or sudo npm install -g ./homebridge-mqttgaragedoor)

and I get:

[2019-05-28T10_57_28_506Z-debug.log](https://github.com/iomax/homebridge-mqttgaragedoor/files/3227254/2019-05-28T10_57_28_506Z-debug.log)
![Schermata 2019-05-28 alle 12 57 56](https://user-images.githubusercontent.com/5991379/58473275-7742b680-8148-11e9-83b5-6532a252644e.png)

Please help me! thanks

**Comment by iomax** [comment]
Sorry, I can help here. 

`sudo npm install -g homebridge-mqttgaragedoor `

Should do the work without issues. I'd remove the homebridge-mqttgaragedoor dir and restart from git clone.

**Comment by manimac79** [comment]
Cool, thanks
