### ISSUE TITLE
Status shows as Stopped

### ISSUE THREAD

**Issue by hemant5400z** [iomax/homebridge-mqttgaragedoor#19]
Hi,

Not sure why but I get Stooped as status when opening the door and a orange question mark, seems obstruction is detected but not sure why, did not do any obstruction detection.

Cheers,
Hemant

**Comment by iomax** [comment]
I'd investigate if the device are still connect to the wifi as the "lwt" and "lwtPayload" config.

**Comment by hemant5400z** [comment]
The device is connect to the wifi i'm monitoring it, but when I publish Open from the reed switch the Homebridge log shows stopped not sure what it is expecting.

I have a relay that drives the door and a reed that checks the status, the relay is set for pulsetime as i have a pulse button connected to the relay so control it from Homekit and using the button.

Hemant

**Comment by hemant5400z** [comment]
My payload is:
"lwtPayload": "tele/garage/LWT"


Here is the config:


{
            "accessory": "mqttgaragedoor",
            "name": "Garagedeur",
            "url": "mqtt://",
            "caption": "Garagedeur",
            "lwtPayload": "tele/lctech/LWT",
            "topics": {
                "statusSet": "cmnd/lctech/POWER1",
                "openGet": "stat/lctech/garagesensor",
                "openValue": 1,
                "closedGet": "stat/lctech/garagesensor",
                "closedValue": 0,
                "openStatusCmd": "TOGGLE",
                "closeStatusCmd": "TOGGLE"

            },
            "doorRunInSeconds": "15"
        },

**Comment by iomax** [comment]
I'd try

`
"lwt":"tele/lctech/LWT",
"lwtpayload" :"Offline"
`

**Comment by hemant5400z** [comment]
added your line: In the Homebridge log I see:

[Garagedeur] Garge Door is stopped

Hemant

**Comment by iomax** [comment]
To get the open status and closed status you have to set 2 different reed. In case of one reed you can get just closed status.
In this case you'll have to set just "closedGet" and the Home app will show "opening" then "open" after the  "doorRunInSeconds" sec. or "closing" then "closed" as the reed will be triggered by the door and if the trigger will not happen within the "doorRunInSeconds" time-window the "obstruction" will be highlighted.
The same will be if your reed is at the full open position, just set openGet in this case.

**Comment by hemant5400z** [comment]
Hi,

For some reason it seems to work now.

I published one topic for open and one for close, they are pointing to the same switch and now I have correct status controlling from homekit and for the button or anywhere else.

The weird stop status is not showing anymore so fixed for me; thanks for your help.

Hemant

**Comment by iomax** [comment]
With just one reed switch it can work but the "running" status will not show in the app.
Honestly it's hard for me to understand how you can place just one switch at the full open position and at the same time the same switch ready to get the door closed state, could you help me, showing something more about your setup ?

**Comment by hemant5400z** [comment]
Hi,

This is my config:
{
            "accessory": "mqttgaragedoor",
            "name": "Garagedeur",
            "url": "mqtt://xxxxxxxxx:1883",
            "caption": "Garagedeur",
            "lwt": "tele/lctech/LWT",
            "lwtpayload": "Offline",
            "topics": {
                "statusSet": "cmnd/lctech/POWER1",
                "openGet": "stat/lctech/open",
                "openValue": 1,
                "closedGet": "stat/lctech/closed",
                "closedValue": 0,
                "openStatusCmd": "TOGGLE",
                "closeStatusCmd": "TOGGLE"
            },
            "doorRunInSeconds": "20"
        }


Which works with openening and closing and shows me all correctly with one reed with, rules are published with tasmota to make sure right status is displayed when controlled with button or garage remote.

Cheers,
Hemant
