### ISSUE TITLE
How to pass message to topic

### ISSUE THREAD

**Issue by hubbardsw** [iomax/homebridge-mqttgaragedoor#2]
I have an ESP 8266 that works just fine in mqtt when using as a regular switch. I pass "1" to the setStatus topic activate a relay for a garage door. However, in your plugin, what value is being passed to the setStatus by default and how to I override it to send message "1"?

Nothing I try works

**Comment by iomax** [comment]
Please try with "on" value. Unfortunately, at this time, if you can not manage it in your esp8266 code, you have to change it inside the homebridge-mqttgaragedoor code ( index.js - row 204 ).

**Comment by MrBalonio** [comment]
This is resolved by https://github.com/iomax/homebridge-mqttgaragedoor/pull/7/

Please merge
