### ISSUE TITLE
As gate opener?

### ISSUE THREAD

**Issue by timhng** [iomax/homebridge-mqttgaragedoor#4]
I’ve now got mqttgaragedoor working beautifully with my garage door and Reed switch. I can now replicate the same setup for my electric gate. The only issue I see is purely cosmetic - the icon in the Apple Home app will be a garage door instead of a gate.
Is there any way of changing this icon?

**Comment by iomax** [comment]
Never tried before anyway I'd try changing the service type declaration in index.js, ( row 79 ), from

` this.garageDoorOpener = new Service.GarageDoorOpener(this.name);`

to

`this.garageDoorOpener = new Service.Door(this.name);`

**Comment by aquadat0r** [comment]
@timhng +1 on this idea

**Comment by timhng** [comment]
Thanks @iomax, so I clone the project and make the code change locally. Then how do I run the new code when the original version is already installed?

**Comment by iomax** [comment]
I'd make the changes to the code already cloned locally and when ready to run, _npm install -g ./homebridge-mqttgaragedoor_ should reinstall it over the previous/original one.
