### ISSUE TITLE
Problems / Setup help with Tasmota

### ISSUE THREAD

**Issue by Kepete** [iomax/homebridge-mqttgaragedoor#9]
This looks to be the exact plugin I was looking for, but I'm having problems to set it up correctly. 

I have a ESP with tasmota firmware. I have connected two reed/magentic switches and one relay. 
My config: 

```
"topics": {
                "statusSet": "cmnd/sonoff_test/POWER3",
                "openGet": "stat/sonoff_test/POWER1",
                "openValue": "ON",
                "closedGet": "stat/sonoff_test/POWER2",
                "closedValue": "ON",
                "openStatusCmdTopic": "stat/sonoff_test/POWER1",
                "openStatusCmd": "ON",
                "closeStatusCmdTopic": "stat/sonoff_test/POWER2",
                "closeStatusCmd": "ON"
            }
        }
    ]
```
Open reed switch is the POWER1, closed reed switch is POWER2 and relay is on POWER3. 

**My logic here was:**
I press the icon in home app, POWER3 toggels the relay, the gate started moving and POWER2 turns from ON to OFF. Gate reaches the most open state and POWER1 turns from OFF to ON. Now after 30 seconds my gate automatically starts closing again, POWER1 turns from ON to OFF. Gate reaches closed position POWER2 turns from OFF to ON. 

**What works** 
Pressing the icon toggles the relay 👍 
Most of the times the POWER 1 turns the state to OPEN
Most of the times the POWER 2 turns the state to CLOSED

**The problem** 
State CLOSING and state OPENING are behaving erratically. Once the OPENING shows, but after that CLOSING doesn't happen and it goes straight from OPEN to CLOSED. Same thing the other way around. 
Sometimes if you press the icon and it goes right into OPENING but the gate takes 1-2 seconds until the reed switch is opened. Then the state turns back into CLOSED. How can it turn back into CLOSED when the POWER2 turns from ON to OFF. ON means it is closed, but it sends the command OFF? 
And lot's of other similar behaviour what is hard to repeat or understand the logic. 

Is my setup wrong?

**Comment by iomax** [comment]
At the start I'd try without the "openStatusCmdTopic"/"openStatusCmd",   "closeStatusCmdTopic"/"closedStatusCmd" as well.

Every time a reed switch change the status, a feedback will be provided through the "open(close)Get" topic and "open(closed)StatusCmdTopic" force the feedback provision even without any change so I don't belive that the same value ( mqtt topic in this case ) for boths, could be the right choice.

**Comment by Kepete** [comment]
Tried it without "openStatusCmdTopic"/"openStatusCmd", "closeStatusCmdTopic"/"closedStatusCmd"
```
"topics": {
                "statusSet": "cmnd/sonoff_test/POWER3",
                "openGet": "stat/sonoff_test/POWER1",
                "openValue": "ON",
                "closedGet": "stat/sonoff_test/POWER2",
                "closedValue": "ON",
            }
        }
```

There are still problems with it. 
First, when I click it to OPEN, then it goes to OPENING but just for 1 second, because as soon as the gate motor start moving and the fully closed reed switch moves away(turns into OFF) the state goes back to CLOSED. But actually it is moving. 
So I'm now on my desk and simulate a gate. If I press open and don't move the "gate"/ POWER2 switch then it's state is OPENING. As soon as I remove the POWER2 reed switch it goes back to CLOSED. Why does this happen if the `"closedValue": "ON"` and POWER2 sends MQTT message OFF ?

**Comment by Kepete** [comment]
So I added now also the `"doorRunInSeconds": "OPEN/CLOSE RUN TIME IN SECONDS",` parameter. 
Now I think it kind of works maybe (?) 

I press it to OPEN , the POWER2 turns from ON to OFF and the state in home app is OPENING. And if the POWER1 switch goes to ON it is OPEN. 

If the gate get's stuck in the way from fully closed to open then the status in app goes from OPENING back to CLOSED. But actually the gate is open. 

Here comes the question is `"doorRunInSeconds"` really needed? Why do we need it if the state can be changed according to the two sensors? 
Would also be a solution to the problem described above.

**Comment by iomax** [comment]
"doorRunInSeconds" should be useful just in case of only one switch ( open or closed signal ) as setup like mine.
Please let me to investigate but some further check from your side could be useful.

Please could you confirm :
- POWER 1 keeps the ON state as the door is fully open and OFF otherwise
- POWER 2 keeps the ON state as the door is fully closed and OFF otherwise
- without "openStatusCmdTopic"/"openStatusCmd", "closeStatusCmdTopic"/"closedStatusCmd",  no messages sent to the various "get" topics but just at the switch state change ( and according at the above "rules" )

**Comment by Kepete** [comment]
Yes, I confirm all these three points. 
Checked the MQTT broker, no other messages are sent to the topic.

**Comment by iomax** [comment]
I've to confirm ... seems that something went wrong in case where you configure two switches and at this time "doorRunInSeconds" did the trick ( I'd configure it slight longer that real operational time ).

Some code rework must be done and I'll keep you updated about it.
Thanks to highlighted it.

**Comment by Kepete** [comment]
Yes right now the "doorRunInSeconds" does the job for most cases. 
But as I have two switches it would be awesome not to configure it at all. 

I will be waiting for the update, thanks! :)

**Comment by iomax** [comment]
Code reworked.
 "doorRunInSeconds" (still) mandatory and it will be set at 20 sec. if undefined.
Obstruction detected set in all cases where the target position (open or closed ) not reached within the  door run time.
The open or closure switches will update the Homekit app as soon as hit, so I'd set the  "doorRunInSeconds" slighting longer than real run time.

**Comment by Kepete** [comment]
Awesome! Tested and it works like supposed 👍 Thank you for your efforts. 

The only thing(it's not the most important) I' missing is the stop function. 
Something like described in #8 . 
Or like this plugin works with stop: https://github.com/corymayer/homebridge-rpi-garagedoor-liftmaster#readme
